name: Build plugin
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 8
              uses: actions/setup-java@v2
              with:
                  java-version: "8"
                  distribution: "adopt"

            - name: Build and package
              run: mvn -B package

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: target/*.jar
